# -*- coding: utf-8 -*-

"""
    mundiapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import mundiapi.models.create_clear_sale_request

class CreateAntifraudRequest(object):

    """Implementation of the 'CreateAntifraudRequest' model.

    TODO: type model description here.

    Attributes:
        mtype (string): TODO: type description here.
        clearsale (CreateClearSaleRequest): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype":'type',
        "clearsale":'clearsale'
    }

    def __init__(self,
                 mtype=None,
                 clearsale=None):
        """Constructor for the CreateAntifraudRequest class"""

        # Initialize members of the class
        self.mtype = mtype
        self.clearsale = clearsale


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get('type')
        clearsale = mundiapi.models.create_clear_sale_request.CreateClearSaleRequest.from_dictionary(dictionary.get('clearsale')) if dictionary.get('clearsale') else None

        # Return an object of this model
        return cls(mtype,
                   clearsale)


