/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateGooglePayRequest
 */
class CreateGooglePayRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.version = this.constructor.getValue(obj.version);
        this.data = this.constructor.getValue(obj.data);
        this.header = this.constructor.getValue(obj.header);
        this.signature = this.constructor.getValue(obj.signature);
        this.merchantIdentifier =
          this.constructor.getValue(obj.merchantIdentifier
     || obj.merchant_identifier);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'version', realName: 'version' },
            { name: 'data', realName: 'data' },
            { name: 'header', realName: 'header', type: 'CreateGooglePayHeaderRequest' },
            { name: 'signature', realName: 'signature' },
            { name: 'merchantIdentifier', realName: 'merchant_identifier' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateGooglePayRequest;
