/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateThreeDSecureRequest
 */
class CreateThreeDSecureRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.mpi = this.constructor.getValue(obj.mpi);
        this.cavv = this.constructor.getValue(obj.cavv);
        this.eci = this.constructor.getValue(obj.eci);
        this.transactionId = this.constructor.getValue(obj.transactionId || obj.transaction_id);
        this.successUrl = this.constructor.getValue(obj.successUrl || obj.success_url);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'mpi', realName: 'mpi' },
            { name: 'cavv', realName: 'cavv' },
            { name: 'eci', realName: 'eci' },
            { name: 'transactionId', realName: 'transaction_id' },
            { name: 'successUrl', realName: 'success_url' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateThreeDSecureRequest;
