/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateTransferSettingsRequest
 */
class CreateTransferSettingsRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.transferEnabled =
          this.constructor.getValue(obj.transferEnabled
     || obj.transfer_enabled);
        this.transferInterval =
          this.constructor.getValue(obj.transferInterval
     || obj.transfer_interval);
        this.transferDay = this.constructor.getValue(obj.transferDay || obj.transfer_day);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'transferEnabled', realName: 'transfer_enabled' },
            { name: 'transferInterval', realName: 'transfer_interval' },
            { name: 'transferDay', realName: 'transfer_day' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateTransferSettingsRequest;
