/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateBoletoPaymentRequest
 */
class CreateBoletoPaymentRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.retries = this.constructor.getValue(obj.retries);
        this.bank = this.constructor.getValue(obj.bank);
        this.instructions = this.constructor.getValue(obj.instructions);
        this.dueAt = this.constructor.getValue(obj.dueAt || obj.due_at);
        this.billingAddress = this.constructor.getValue(obj.billingAddress || obj.billing_address);
        this.billingAddressId =
          this.constructor.getValue(obj.billingAddressId
     || obj.billing_address_id);
        this.nossoNumero = this.constructor.getValue(obj.nossoNumero || obj.nosso_numero);
        this.documentNumber = this.constructor.getValue(obj.documentNumber || obj.document_number);
        this.interest = this.constructor.getValue(obj.interest);
        this.fine = this.constructor.getValue(obj.fine);
        this.maxDaysToPayPastDue =
          this.constructor.getValue(obj.maxDaysToPayPastDue
     || obj.max_days_to_pay_past_due);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'retries', realName: 'retries' },
            { name: 'bank', realName: 'bank' },
            { name: 'instructions', realName: 'instructions' },
            { name: 'dueAt', realName: 'due_at', isDateTime: true, dateTimeValue: 'rfc3339' },
            { name: 'billingAddress', realName: 'billing_address', type: 'BillingAddress1' },
            { name: 'billingAddressId', realName: 'billing_address_id' },
            { name: 'nossoNumero', realName: 'nosso_numero' },
            { name: 'documentNumber', realName: 'document_number' },
            { name: 'interest', realName: 'interest', type: 'Interest' },
            { name: 'fine', realName: 'fine', type: 'Fine' },
            { name: 'maxDaysToPayPastDue', realName: 'max_days_to_pay_past_due' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateBoletoPaymentRequest;
