/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateCardTokenRequest
 */
class CreateCardTokenRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.number = this.constructor.getValue(obj.number);
        this.holderName = this.constructor.getValue(obj.holderName || obj.holder_name);
        this.expMonth = this.constructor.getValue(obj.expMonth || obj.exp_month);
        this.expYear = this.constructor.getValue(obj.expYear || obj.exp_year);
        this.cvv = this.constructor.getValue(obj.cvv);
        this.brand = this.constructor.getValue(obj.brand);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'number', realName: 'number' },
            { name: 'holderName', realName: 'holder_name' },
            { name: 'expMonth', realName: 'exp_month' },
            { name: 'expYear', realName: 'exp_year' },
            { name: 'cvv', realName: 'cvv' },
            { name: 'brand', realName: 'brand' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateCardTokenRequest;
