/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateChargeRequest
 */
class CreateChargeRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.code = this.constructor.getValue(obj.code);
        this.amount = this.constructor.getValue(obj.amount);
        this.customerId = this.constructor.getValue(obj.customerId || obj.customer_id);
        this.customer = this.constructor.getValue(obj.customer);
        this.payment = this.constructor.getValue(obj.payment);
        this.metadata = this.constructor.getValue(obj.metadata);
        this.dueAt = this.constructor.getValue(obj.dueAt || obj.due_at);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'code', realName: 'code' },
            { name: 'amount', realName: 'amount' },
            { name: 'customerId', realName: 'customer_id' },
            { name: 'customer', realName: 'customer', type: 'CreateCustomerRequest' },
            { name: 'payment', realName: 'payment', type: 'CreatePaymentRequest' },
            { name: 'metadata', realName: 'metadata' },
            { name: 'dueAt', realName: 'due_at', isDateTime: true, dateTimeValue: 'rfc3339' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateChargeRequest;
