/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateCreditCardPaymentRequest
 */
class CreateCreditCardPaymentRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.installments = this.constructor.getValue(obj.installments, 1);
        this.statementDescriptor =
          this.constructor.getValue(obj.statementDescriptor
     || obj.statement_descriptor);
        this.card = this.constructor.getValue(obj.card);
        this.cardId = this.constructor.getValue(obj.cardId || obj.card_id);
        this.cardToken = this.constructor.getValue(obj.cardToken || obj.card_token);
        this.recurrence = this.constructor.getValue(obj.recurrence);
        this.capture = this.constructor.getValue(obj.capture, true);
        this.extendedLimitEnabled =
          this.constructor.getValue(obj.extendedLimitEnabled
     || obj.extended_limit_enabled);
        this.extendedLimitCode =
          this.constructor.getValue(obj.extendedLimitCode
     || obj.extended_limit_code);
        this.merchantCategoryCode =
          this.constructor.getValue(obj.merchantCategoryCode
     || obj.merchant_category_code);
        this.authentication = this.constructor.getValue(obj.authentication);
        this.contactless = this.constructor.getValue(obj.contactless);
        this.autoRecovery = this.constructor.getValue(obj.autoRecovery || obj.auto_recovery);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'installments', realName: 'installments' },
            { name: 'statementDescriptor', realName: 'statement_descriptor' },
            { name: 'card', realName: 'card', type: 'CreateCardRequest' },
            { name: 'cardId', realName: 'card_id' },
            { name: 'cardToken', realName: 'card_token' },
            { name: 'recurrence', realName: 'recurrence' },
            { name: 'capture', realName: 'capture' },
            { name: 'extendedLimitEnabled', realName: 'extended_limit_enabled' },
            { name: 'extendedLimitCode', realName: 'extended_limit_code' },
            { name: 'merchantCategoryCode', realName: 'merchant_category_code' },
            {
                name: 'authentication',
                realName: 'authentication',
                type: 'CreatePaymentAuthenticationRequest',
            },
            { name: 'contactless', realName: 'contactless', type: 'CreateCardPaymentTokenRequest' },
            { name: 'autoRecovery', realName: 'auto_recovery' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateCreditCardPaymentRequest;
