/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of GetCardResponse
 */
class GetCardResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.lastFourDigits = this.constructor.getValue(obj.lastFourDigits || obj.last_four_digits);
        this.brand = this.constructor.getValue(obj.brand);
        this.holderName = this.constructor.getValue(obj.holderName || obj.holder_name);
        this.expMonth = this.constructor.getValue(obj.expMonth || obj.exp_month);
        this.expYear = this.constructor.getValue(obj.expYear || obj.exp_year);
        this.status = this.constructor.getValue(obj.status);
        this.createdAt = this.constructor.getValue(obj.createdAt || obj.created_at);
        this.updatedAt = this.constructor.getValue(obj.updatedAt || obj.updated_at);
        this.billingAddress = this.constructor.getValue(obj.billingAddress || obj.billing_address);
        this.customer = this.constructor.getValue(obj.customer);
        this.metadata = this.constructor.getValue(obj.metadata);
        this.type = this.constructor.getValue(obj.type);
        this.holderDocument = this.constructor.getValue(obj.holderDocument || obj.holder_document);
        this.deletedAt = this.constructor.getValue(obj.deletedAt || obj.deleted_at);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'lastFourDigits', realName: 'last_four_digits' },
            { name: 'brand', realName: 'brand' },
            { name: 'holderName', realName: 'holder_name' },
            { name: 'expMonth', realName: 'exp_month' },
            { name: 'expYear', realName: 'exp_year' },
            { name: 'status', realName: 'status' },
            {
                name: 'createdAt',
                realName: 'created_at',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'updatedAt',
                realName: 'updated_at',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'billingAddress',
                realName: 'billing_address',
                type: 'GetBillingAddressResponse',
            },
            { name: 'customer', realName: 'customer', type: 'GetCustomerResponse' },
            { name: 'metadata', realName: 'metadata' },
            { name: 'type', realName: 'type' },
            { name: 'holderDocument', realName: 'holder_document' },
            {
                name: 'deletedAt',
                realName: 'deleted_at',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = GetCardResponse;
