/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of GetInvoiceItemResponse
 */
class GetInvoiceItemResponse extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.amount = this.constructor.getValue(obj.amount);
        this.description = this.constructor.getValue(obj.description);
        this.pricingScheme = this.constructor.getValue(obj.pricingScheme || obj.pricing_scheme);
        this.priceBracket = this.constructor.getValue(obj.priceBracket || obj.price_bracket);
        this.quantity = this.constructor.getValue(obj.quantity);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'amount', realName: 'amount' },
            { name: 'description', realName: 'description' },
            { name: 'pricingScheme', realName: 'pricing_scheme', type: 'GetPricingSchemeResponse' },
            { name: 'priceBracket', realName: 'price_bracket', type: 'GetPriceBracketResponse' },
            { name: 'quantity', realName: 'quantity' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = GetInvoiceItemResponse;
