/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ListSubscriptionsResponse = require('../lib/Models/ListSubscriptionsResponse');
const UpdatePriceBracketRequest = require('../lib/Models/UpdatePriceBracketRequest');
const GetPlanResponse = require('../lib/Models/GetPlanResponse');
const CreatePhonesRequest = require('../lib/Models/CreatePhonesRequest');
const UpdateMetadataRequest = require('../lib/Models/UpdateMetadataRequest');
const GetCheckoutPaymentSettingsResponse =
  require('../lib/Models/GetCheckoutPaymentSettingsResponse');
const UpdateCustomerRequest = require('../lib/Models/UpdateCustomerRequest');
const CreateBoletoPaymentRequest = require('../lib/Models/CreateBoletoPaymentRequest');
const CreateDiscountRequest = require('../lib/Models/CreateDiscountRequest');
const CreateIncrementRequest = require('../lib/Models/CreateIncrementRequest');
const ListIncrementsResponse = require('../lib/Models/ListIncrementsResponse');
const GetGatewayResponseResponse = require('../lib/Models/GetGatewayResponseResponse');
const GetPaymentAuthenticationResponse = require('../lib/Models/GetPaymentAuthenticationResponse');
const UpdateSubscriptionPaymentMethodRequest =
  require('../lib/Models/UpdateSubscriptionPaymentMethodRequest');
const GetChargeResponse = require('../lib/Models/GetChargeResponse');
const CreateDeviceRequest = require('../lib/Models/CreateDeviceRequest');
const GetLocationResponse = require('../lib/Models/GetLocationResponse');
const GetUsagesDetailsResponse = require('../lib/Models/GetUsagesDetailsResponse');
const CreatePaymentAuthenticationRequest =
  require('../lib/Models/CreatePaymentAuthenticationRequest');
const CreateApplePayRequest = require('../lib/Models/CreateApplePayRequest');
const UpdateSubscriptionMinimumPriceRequest =
  require('../lib/Models/UpdateSubscriptionMinimumPriceRequest');
const CreateCancelChargeRequest = require('../lib/Models/CreateCancelChargeRequest');
const GetThreeDSecureResponse = require('../lib/Models/GetThreeDSecureResponse');
const GetCheckoutDebitCardPaymentResponse =
  require('../lib/Models/GetCheckoutDebitCardPaymentResponse');
const CreateSplitOptionsRequest = require('../lib/Models/CreateSplitOptionsRequest');
const CreateGooglePayHeaderRequest = require('../lib/Models/CreateGooglePayHeaderRequest');
const GetInvoiceResponse = require('../lib/Models/GetInvoiceResponse');
const ListInvoicesResponse = require('../lib/Models/ListInvoicesResponse');
const CreatePriceBracketRequest = require('../lib/Models/CreatePriceBracketRequest');
const CreateCheckoutBoletoPaymentRequest =
  require('../lib/Models/CreateCheckoutBoletoPaymentRequest');
const CreateBankAccountRequest = require('../lib/Models/CreateBankAccountRequest');
const ListAnticipationResponse = require('../lib/Models/ListAnticipationResponse');
const CreateLocationRequest = require('../lib/Models/CreateLocationRequest');
const UpdateTransferSettingsRequest = require('../lib/Models/UpdateTransferSettingsRequest');
const CreatePaymentRequest = require('../lib/Models/CreatePaymentRequest');
const GetAddressResponse = require('../lib/Models/GetAddressResponse');
const GetCheckoutBoletoPaymentResponse = require('../lib/Models/GetCheckoutBoletoPaymentResponse');
const UpdateSubscriptionItemRequest = require('../lib/Models/UpdateSubscriptionItemRequest');
const CreateSetupRequest = require('../lib/Models/CreateSetupRequest');
const CreatePricingSchemeRequest = require('../lib/Models/CreatePricingSchemeRequest');
const UpdatePricingSchemeRequest = require('../lib/Models/UpdatePricingSchemeRequest');
const GetPlanItemResponse = require('../lib/Models/GetPlanItemResponse');
const GetBankTransferTransactionResponse =
  require('../lib/Models/GetBankTransferTransactionResponse');
const GetTransferResponse = require('../lib/Models/GetTransferResponse');
const CreateSubscriptionItemRequest = require('../lib/Models/CreateSubscriptionItemRequest');
const CreateSubscriptionRequest = require('../lib/Models/CreateSubscriptionRequest');
const CreateOrderRequest = require('../lib/Models/CreateOrderRequest');
const CreateRecipientRequest = require('../lib/Models/CreateRecipientRequest');
const CreateDebitCardPaymentRequest = require('../lib/Models/CreateDebitCardPaymentRequest');
const GetDebitCardTransactionResponse = require('../lib/Models/GetDebitCardTransactionResponse');
const CreateOrderItemRequest = require('../lib/Models/CreateOrderItemRequest');
const GetTransactionReportFileResponse = require('../lib/Models/GetTransactionReportFileResponse');
const ListUsagesResponse = require('../lib/Models/ListUsagesResponse');
const ListCardsResponse = require('../lib/Models/ListCardsResponse');
const GetPriceBracketResponse = require('../lib/Models/GetPriceBracketResponse');
const UpdateChargeCardRequest = require('../lib/Models/UpdateChargeCardRequest');
const UpdateRecipientRequest = require('../lib/Models/UpdateRecipientRequest');
const GetAnticipationLimitResponse = require('../lib/Models/GetAnticipationLimitResponse');
const CreateCancelChargeSplitRulesRequest =
  require('../lib/Models/CreateCancelChargeSplitRulesRequest');
const GetAnticipationResponse = require('../lib/Models/GetAnticipationResponse');
const CreateCheckoutCardInstallmentOptionRequest =
  require('../lib/Models/CreateCheckoutCardInstallmentOptionRequest');
const CreateCheckoutDebitCardPaymentRequest =
  require('../lib/Models/CreateCheckoutDebitCardPaymentRequest');
const CreateAnticipationRequest = require('../lib/Models/CreateAnticipationRequest');
const UpdateOrderStatusRequest = require('../lib/Models/UpdateOrderStatusRequest');
const UpdateSubscriptionDueDaysRequest = require('../lib/Models/UpdateSubscriptionDueDaysRequest');
const ListChargeTransactionsResponse = require('../lib/Models/ListChargeTransactionsResponse');
const ListCyclesResponse = require('../lib/Models/ListCyclesResponse');
const CreateCardOptionsRequest = require('../lib/Models/CreateCardOptionsRequest');
const GetPhoneResponse = require('../lib/Models/GetPhoneResponse');
const CreateCardTokenRequest = require('../lib/Models/CreateCardTokenRequest');
const GetTokenResponse = require('../lib/Models/GetTokenResponse');
const GetRecipientResponse = require('../lib/Models/GetRecipientResponse');
const GetIncrementResponse = require('../lib/Models/GetIncrementResponse');
const GetPeriodResponse = require('../lib/Models/GetPeriodResponse');
const UpdateChargePaymentMethodRequest = require('../lib/Models/UpdateChargePaymentMethodRequest');
const GetTransactionResponse = require('../lib/Models/GetTransactionResponse');
const GetCheckoutPaymentResponse = require('../lib/Models/GetCheckoutPaymentResponse');
const CreateCardRequest = require('../lib/Models/CreateCardRequest');
const GetAccessTokenResponse = require('../lib/Models/GetAccessTokenResponse');
const ListChargesResponse = require('../lib/Models/ListChargesResponse');
const GetOrderResponse = require('../lib/Models/GetOrderResponse');
const CreatePlanItemRequest = require('../lib/Models/CreatePlanItemRequest');
const GetBillingAddressResponse = require('../lib/Models/GetBillingAddressResponse');
const CreateApplePayHeaderRequest = require('../lib/Models/CreateApplePayHeaderRequest');
const CreateChargeRequest = require('../lib/Models/CreateChargeRequest');
const CreateCustomerRequest = require('../lib/Models/CreateCustomerRequest');
const CreateCancelSubscriptionRequest = require('../lib/Models/CreateCancelSubscriptionRequest');
const ListAccessTokensResponse = require('../lib/Models/ListAccessTokensResponse');
const CreateTransferRequest = require('../lib/Models/CreateTransferRequest');
const ListRecipientResponse = require('../lib/Models/ListRecipientResponse');
const GetBalanceResponse = require('../lib/Models/GetBalanceResponse');
const GetUsageResponse = require('../lib/Models/GetUsageResponse');
const CreateCreditCardPaymentRequest = require('../lib/Models/CreateCreditCardPaymentRequest');
const ListDiscountsResponse = require('../lib/Models/ListDiscountsResponse');
const CreateUsageRequest = require('../lib/Models/CreateUsageRequest');
const GetSubscriptionResponse = require('../lib/Models/GetSubscriptionResponse');
const GetSubscriptionItemResponse = require('../lib/Models/GetSubscriptionItemResponse');
const GetCardResponse = require('../lib/Models/GetCardResponse');
const GetSplitResponse = require('../lib/Models/GetSplitResponse');
const CreateCheckoutPaymentRequest = require('../lib/Models/CreateCheckoutPaymentRequest');
const CreateCheckoutBankTransferRequest =
  require('../lib/Models/CreateCheckoutBankTransferRequest');
const ListPlansResponse = require('../lib/Models/ListPlansResponse');
const CreateAccessTokenRequest = require('../lib/Models/CreateAccessTokenRequest');
const GetDiscountResponse = require('../lib/Models/GetDiscountResponse');
const GetVoucherTransactionResponse = require('../lib/Models/GetVoucherTransactionResponse');
const CreateTokenRequest = require('../lib/Models/CreateTokenRequest');
const UpdateInvoiceStatusRequest = require('../lib/Models/UpdateInvoiceStatusRequest');
const UpdateAddressRequest = require('../lib/Models/UpdateAddressRequest');
const GetBoletoTransactionResponse = require('../lib/Models/GetBoletoTransactionResponse');
const GetInvoiceItemResponse = require('../lib/Models/GetInvoiceItemResponse');
const GetCheckoutCreditCardPaymentResponse =
  require('../lib/Models/GetCheckoutCreditCardPaymentResponse');
const UpdateCardRequest = require('../lib/Models/UpdateCardRequest');
const GetSetupResponse = require('../lib/Models/GetSetupResponse');
const CreatePlanRequest = require('../lib/Models/CreatePlanRequest');
const CreateVoucherPaymentRequest = require('../lib/Models/CreateVoucherPaymentRequest');
const CreateBankTransferPaymentRequest = require('../lib/Models/CreateBankTransferPaymentRequest');
const CreateShippingRequest = require('../lib/Models/CreateShippingRequest');
const GetShippingResponse = require('../lib/Models/GetShippingResponse');
const CreateSplitRequest = require('../lib/Models/CreateSplitRequest');
const CreateInvoiceRequest = require('../lib/Models/CreateInvoiceRequest');
const UpdateSubscriptionBillingDateRequest =
  require('../lib/Models/UpdateSubscriptionBillingDateRequest');
const ListAddressesResponse = require('../lib/Models/ListAddressesResponse');
const GetGatewayErrorResponse = require('../lib/Models/GetGatewayErrorResponse');
const CreatePeriodRequest = require('../lib/Models/CreatePeriodRequest');
const CreateCheckoutCreditCardPaymentRequest =
  require('../lib/Models/CreateCheckoutCreditCardPaymentRequest');
const CreateAntifraudRequest = require('../lib/Models/CreateAntifraudRequest');
const GetAntifraudResponse = require('../lib/Models/GetAntifraudResponse');
const UpdatePlanItemRequest = require('../lib/Models/UpdatePlanItemRequest');
const CreateAddressRequest = require('../lib/Models/CreateAddressRequest');
const GetAnticipationLimitsResponse = require('../lib/Models/GetAnticipationLimitsResponse');
const UpdateSubscriptionAffiliationIdRequest =
  require('../lib/Models/UpdateSubscriptionAffiliationIdRequest');
const CreateCashPaymentRequest = require('../lib/Models/CreateCashPaymentRequest');
const CreateConfirmPaymentRequest = require('../lib/Models/CreateConfirmPaymentRequest');
const GetCashTransactionResponse = require('../lib/Models/GetCashTransactionResponse');
const UpdateCurrentCycleStatusRequest = require('../lib/Models/UpdateCurrentCycleStatusRequest');
const GetCheckoutBankTransferPaymentResponse =
  require('../lib/Models/GetCheckoutBankTransferPaymentResponse');
const GetCheckoutCardInstallmentOptionsResponse =
  require('../lib/Models/GetCheckoutCardInstallmentOptionsResponse');
const ListSubscriptionItemsResponse = require('../lib/Models/ListSubscriptionItemsResponse');
const UpdateSubscriptionCardRequest = require('../lib/Models/UpdateSubscriptionCardRequest');
const GetCustomerResponse = require('../lib/Models/GetCustomerResponse');
const CreatePhoneRequest = require('../lib/Models/CreatePhoneRequest');
const GetPhonesResponse = require('../lib/Models/GetPhonesResponse');
const CreateCaptureChargeRequest = require('../lib/Models/CreateCaptureChargeRequest');
const GetSafetyPayTransactionResponse = require('../lib/Models/GetSafetyPayTransactionResponse');
const ListTransferResponse = require('../lib/Models/ListTransferResponse');
const GetDeviceResponse = require('../lib/Models/GetDeviceResponse');
const UpdateOrderItemRequest = require('../lib/Models/UpdateOrderItemRequest');
const ListUsagesDetailsResponse = require('../lib/Models/ListUsagesDetailsResponse');
const CreateTransferSettingsRequest = require('../lib/Models/CreateTransferSettingsRequest');
const CreateTransactionReportFileRequest =
  require('../lib/Models/CreateTransactionReportFileRequest');
const ListTransactionsFilesResponse = require('../lib/Models/ListTransactionsFilesResponse');
const CreateGooglePayRequest = require('../lib/Models/CreateGooglePayRequest');
const UpdateChargeDueDateRequest = require('../lib/Models/UpdateChargeDueDateRequest');
const ListCustomersResponse = require('../lib/Models/ListCustomersResponse');
const GetPricingSchemeResponse = require('../lib/Models/GetPricingSchemeResponse');
const UpdateRecipientBankAccountRequest =
  require('../lib/Models/UpdateRecipientBankAccountRequest');
const CreateThreeDSecureRequest = require('../lib/Models/CreateThreeDSecureRequest');
const GetCreditCardTransactionResponse = require('../lib/Models/GetCreditCardTransactionResponse');
const CreateCardPaymentContactlessRequest =
  require('../lib/Models/CreateCardPaymentContactlessRequest');
const GetBankAccountResponse = require('../lib/Models/GetBankAccountResponse');
const ListOrderResponse = require('../lib/Models/ListOrderResponse');
const ListTransactionsResponse = require('../lib/Models/ListTransactionsResponse');
const PagingResponse = require('../lib/Models/PagingResponse');
const UpdatePlanRequest = require('../lib/Models/UpdatePlanRequest');
const GetCardTokenResponse = require('../lib/Models/GetCardTokenResponse');
const GetGatewayRecipientResponse = require('../lib/Models/GetGatewayRecipientResponse');
const UpdateSubscriptionStartAtRequest = require('../lib/Models/UpdateSubscriptionStartAtRequest');
const UpdateCurrentCycleEndDateRequest = require('../lib/Models/UpdateCurrentCycleEndDateRequest');
const CreateClearSaleRequest = require('../lib/Models/CreateClearSaleRequest');
const GetOrderItemResponse = require('../lib/Models/GetOrderItemResponse');
const CreateEmvDataDecryptRequest = require('../lib/Models/CreateEmvDataDecryptRequest');
const CreateEmvDataTlvDecryptRequest = require('../lib/Models/CreateEmvDataTlvDecryptRequest');
const CreateCardPaymentContactlessPOIRequest =
  require('../lib/Models/CreateCardPaymentContactlessPOIRequest');
const CreateEmvDataDukptDecryptRequest = require('../lib/Models/CreateEmvDataDukptDecryptRequest');
const CreateEmvDecryptRequest = require('../lib/Models/CreateEmvDecryptRequest');
const GetUsageReportResponse = require('../lib/Models/GetUsageReportResponse');
const GetChargesSummaryResponse = require('../lib/Models/GetChargesSummaryResponse');
const CreateWithdrawRequest = require('../lib/Models/CreateWithdrawRequest');
const GetWithdrawTargetResponse = require('../lib/Models/GetWithdrawTargetResponse');
const GetWithdrawSourceResponse = require('../lib/Models/GetWithdrawSourceResponse');
const GetWithdrawResponse = require('../lib/Models/GetWithdrawResponse');
const GetTransferSourceResponse = require('../lib/Models/GetTransferSourceResponse');
const GetTransferTargetResponse = require('../lib/Models/GetTransferTargetResponse');
const GetTransfer = require('../lib/Models/GetTransfer');
const CreateTransfer = require('../lib/Models/CreateTransfer');
const ListTransfers = require('../lib/Models/ListTransfers');
const ListWithdrawals = require('../lib/Models/ListWithdrawals');
const CreatePrivateLabelPaymentRequest = require('../lib/Models/CreatePrivateLabelPaymentRequest');
const GetPrivateLabelTransactionResponse =
  require('../lib/Models/GetPrivateLabelTransactionResponse');
const CreateAutomaticAnticipationSettingsRequest =
  require('../lib/Models/CreateAutomaticAnticipationSettingsRequest');
const UpdateAutomaticAnticipationSettingsRequest =
  require('../lib/Models/UpdateAutomaticAnticipationSettingsRequest');
const GetAutomaticAnticipationResponse = require('../lib/Models/GetAutomaticAnticipationResponse');
const GetSplitOptionsResponse = require('../lib/Models/GetSplitOptionsResponse');
const CreateSubMerchantRequest = require('../lib/Models/CreateSubMerchantRequest');
const GetPixTransactionResponse = require('../lib/Models/GetPixTransactionResponse');
const PixAdditionalInformation = require('../lib/Models/PixAdditionalInformation');
const CreatePixPaymentRequest = require('../lib/Models/CreatePixPaymentRequest');
const GetTransferSettingsResponse = require('../lib/Models/GetTransferSettingsResponse');
const CreateSubscriptionSplitRequest = require('../lib/Models/CreateSubscriptionSplitRequest');
const GetSubscriptionSplitResponse = require('../lib/Models/GetSubscriptionSplitResponse');
const UpdateSubscriptionSplitRequest = require('../lib/Models/UpdateSubscriptionSplitRequest');
const CancelSplitRequest = require('../lib/Models/CancelSplitRequest');
const GetPixPayerResponse = require('../lib/Models/GetPixPayerResponse');
const GetPixBankAccountResponse = require('../lib/Models/GetPixBankAccountResponse');
const GetInterestResponse = require('../lib/Models/GetInterestResponse');
const GetFineResponse = require('../lib/Models/GetFineResponse');
const CreateInterestRequest = require('../lib/Models/CreateInterestRequest');
const CreateFineRequest = require('../lib/Models/CreateFineRequest');
const Address = require('../lib/Models/Address');
const Address1 = require('../lib/Models/Address1');
const ApplePay = require('../lib/Models/ApplePay');
const Authentication = require('../lib/Models/Authentication');
const Authentication2 = require('../lib/Models/Authentication2');
const BankAccount = require('../lib/Models/BankAccount');
const BankAccount1 = require('../lib/Models/BankAccount1');
const BankTransfer = require('../lib/Models/BankTransfer');
const BankTransfer1 = require('../lib/Models/BankTransfer1');
const BankTransfer2 = require('../lib/Models/BankTransfer2');
const BillingAddress = require('../lib/Models/BillingAddress');
const BillingAddress1 = require('../lib/Models/BillingAddress1');
const Billingaddress3 = require('../lib/Models/Billingaddress3');
const Boleto1 = require('../lib/Models/Boleto1');
const Card = require('../lib/Models/Card');
const Card1 = require('../lib/Models/Card1');
const Card9 = require('../lib/Models/Card9');
const Card11 = require('../lib/Models/Card11');
const Charge = require('../lib/Models/Charge');
const ChargesCaptureRequest = require('../lib/Models/ChargesCaptureRequest');
const ChargesCaptureResponse = require('../lib/Models/ChargesCaptureResponse');
const ChargesCardRequest = require('../lib/Models/ChargesCardRequest');
const ChargesCardResponse = require('../lib/Models/ChargesCardResponse');
const ChargesConfirmPaymentResponse = require('../lib/Models/ChargesConfirmPaymentResponse');
const ChargesDueDateRequest = require('../lib/Models/ChargesDueDateRequest');
const ChargesDueDateResponse = require('../lib/Models/ChargesDueDateResponse');
const ChargesMetadataRequest = require('../lib/Models/ChargesMetadataRequest');
const ChargesMetadataResponse = require('../lib/Models/ChargesMetadataResponse');
const ChargesPaymentMethodRequest = require('../lib/Models/ChargesPaymentMethodRequest');
const ChargesPaymentMethodResponse = require('../lib/Models/ChargesPaymentMethodResponse');
const ChargesRequest = require('../lib/Models/ChargesRequest');
const ChargesRequest1 = require('../lib/Models/ChargesRequest1');
const ChargesResponse = require('../lib/Models/ChargesResponse');
const ChargesResponse2 = require('../lib/Models/ChargesResponse2');
const ChargesRetryResponse = require('../lib/Models/ChargesRetryResponse');
const ChargesTransactionsResponse = require('../lib/Models/ChargesTransactionsResponse');
const Checkout = require('../lib/Models/Checkout');
const Contactless = require('../lib/Models/Contactless');
const CreditCard1 = require('../lib/Models/CreditCard1');
const CreditCard2 = require('../lib/Models/CreditCard2');
const CurrentCycle = require('../lib/Models/CurrentCycle');
const Customer = require('../lib/Models/Customer');
const Customer8 = require('../lib/Models/Customer8');
const CustomersAccessTokensRequest = require('../lib/Models/CustomersAccessTokensRequest');
const CustomersAccessTokensResponse = require('../lib/Models/CustomersAccessTokensResponse');
const CustomersAccessTokensResponse1 = require('../lib/Models/CustomersAccessTokensResponse1');
const CustomersAddressesRequest = require('../lib/Models/CustomersAddressesRequest');
const CustomersAddressesRequest1 = require('../lib/Models/CustomersAddressesRequest1');
const CustomersAddressesResponse = require('../lib/Models/CustomersAddressesResponse');
const CustomersAddressesResponse1 = require('../lib/Models/CustomersAddressesResponse1');
const CustomersCardsRenewResponse = require('../lib/Models/CustomersCardsRenewResponse');
const CustomersCardsRequest = require('../lib/Models/CustomersCardsRequest');
const CustomersCardsRequest1 = require('../lib/Models/CustomersCardsRequest1');
const CustomersCardsResponse = require('../lib/Models/CustomersCardsResponse');
const CustomersCardsResponse1 = require('../lib/Models/CustomersCardsResponse1');
const CustomersMetadataRequest = require('../lib/Models/CustomersMetadataRequest');
const CustomersMetadataResponse = require('../lib/Models/CustomersMetadataResponse');
const CustomersRequest = require('../lib/Models/CustomersRequest');
const CustomersRequest1 = require('../lib/Models/CustomersRequest1');
const CustomersResponse = require('../lib/Models/CustomersResponse');
const CustomersResponse3 = require('../lib/Models/CustomersResponse3');
const Cycle = require('../lib/Models/Cycle');
const DebitCard1 = require('../lib/Models/DebitCard1');
const DebitCard2 = require('../lib/Models/DebitCard2');
const DefaultBankAccount = require('../lib/Models/DefaultBankAccount');
const DefaultBankAccount1 = require('../lib/Models/DefaultBankAccount1');
const Device = require('../lib/Models/Device');
const Device1 = require('../lib/Models/Device1');
const Fine = require('../lib/Models/Fine');
const GatewayResponse = require('../lib/Models/GatewayResponse');
const GooglePay = require('../lib/Models/GooglePay');
const Header = require('../lib/Models/Header');
const Header1 = require('../lib/Models/Header1');
const Interest = require('../lib/Models/Interest');
const Invoice = require('../lib/Models/Invoice');
const InvoicesMetadataRequest = require('../lib/Models/InvoicesMetadataRequest');
const InvoicesMetadataResponse = require('../lib/Models/InvoicesMetadataResponse');
const InvoicesResponse = require('../lib/Models/InvoicesResponse');
const InvoicesResponse2 = require('../lib/Models/InvoicesResponse2');
const InvoicesStatusResponse = require('../lib/Models/InvoicesStatusResponse');
const Location = require('../lib/Models/Location');
const Max = require('../lib/Models/Max');
const Min = require('../lib/Models/Min');
const Options1 = require('../lib/Models/Options1');
const Options2 = require('../lib/Models/Options2');
const Order = require('../lib/Models/Order');
const OrdersClosedResponse = require('../lib/Models/OrdersClosedResponse');
const OrdersItemsRequest = require('../lib/Models/OrdersItemsRequest');
const OrdersItemsRequest1 = require('../lib/Models/OrdersItemsRequest1');
const OrdersItemsResponse = require('../lib/Models/OrdersItemsResponse');
const OrdersItemsResponse1 = require('../lib/Models/OrdersItemsResponse1');
const OrdersMetadataRequest = require('../lib/Models/OrdersMetadataRequest');
const OrdersMetadataResponse = require('../lib/Models/OrdersMetadataResponse');
const OrdersRequest = require('../lib/Models/OrdersRequest');
const OrdersResponse = require('../lib/Models/OrdersResponse');
const OrdersResponse1 = require('../lib/Models/OrdersResponse1');
const Paging = require('../lib/Models/Paging');
const Payment = require('../lib/Models/Payment');
const Period = require('../lib/Models/Period');
const Pix = require('../lib/Models/Pix');
const Plan = require('../lib/Models/Plan');
const PlansItemsRequest = require('../lib/Models/PlansItemsRequest');
const PlansItemsRequest1 = require('../lib/Models/PlansItemsRequest1');
const PlansItemsResponse = require('../lib/Models/PlansItemsResponse');
const PlansMetadataRequest = require('../lib/Models/PlansMetadataRequest');
const PlansMetadataResponse = require('../lib/Models/PlansMetadataResponse');
const PlansRequest = require('../lib/Models/PlansRequest');
const PlansRequest1 = require('../lib/Models/PlansRequest1');
const PlansResponse = require('../lib/Models/PlansResponse');
const PlansResponse1 = require('../lib/Models/PlansResponse1');
const PriceBracket = require('../lib/Models/PriceBracket');
const PricingScheme = require('../lib/Models/PricingScheme');
const PricingScheme3 = require('../lib/Models/PricingScheme3');
const PricingScheme4 = require('../lib/Models/PricingScheme4');
const PrivateLabel = require('../lib/Models/PrivateLabel');
const Recipient = require('../lib/Models/Recipient');
const RecipientsAnticipationLimitsResponse =
  require('../lib/Models/RecipientsAnticipationLimitsResponse');
const RecipientsAnticipationsRequest = require('../lib/Models/RecipientsAnticipationsRequest');
const RecipientsAnticipationsResponse = require('../lib/Models/RecipientsAnticipationsResponse');
const RecipientsAnticipationsResponse1 = require('../lib/Models/RecipientsAnticipationsResponse1');
const RecipientsAutomaticAnticipationSettingsResponse =
  require('../lib/Models/RecipientsAutomaticAnticipationSettingsResponse');
const RecipientsBalanceResponse = require('../lib/Models/RecipientsBalanceResponse');
const RecipientsCodeResponse = require('../lib/Models/RecipientsCodeResponse');
const RecipientsDefaultBankAccountRequest =
  require('../lib/Models/RecipientsDefaultBankAccountRequest');
const RecipientsDefaultBankAccountResponse =
  require('../lib/Models/RecipientsDefaultBankAccountResponse');
const RecipientsMetadataRequest = require('../lib/Models/RecipientsMetadataRequest');
const RecipientsMetadataResponse = require('../lib/Models/RecipientsMetadataResponse');
const RecipientsRequest = require('../lib/Models/RecipientsRequest');
const RecipientsRequest1 = require('../lib/Models/RecipientsRequest1');
const RecipientsResponse = require('../lib/Models/RecipientsResponse');
const RecipientsResponse1 = require('../lib/Models/RecipientsResponse1');
const RecipientsTransferSettingsResponse =
  require('../lib/Models/RecipientsTransferSettingsResponse');
const RecipientsTransfersRequest = require('../lib/Models/RecipientsTransfersRequest');
const RecipientsTransfersResponse = require('../lib/Models/RecipientsTransfersResponse');
const RecipientsTransfersResponse1 = require('../lib/Models/RecipientsTransfersResponse1');
const Setup = require('../lib/Models/Setup');
const Setup1 = require('../lib/Models/Setup1');
const Shipping = require('../lib/Models/Shipping');
const Shipping3 = require('../lib/Models/Shipping3');
const Split = require('../lib/Models/Split');
const Submerchant = require('../lib/Models/Submerchant');
const SubscriptionsBillingDateRequest = require('../lib/Models/SubscriptionsBillingDateRequest');
const SubscriptionsCardRequest = require('../lib/Models/SubscriptionsCardRequest');
const SubscriptionsCyclesPayRequest = require('../lib/Models/SubscriptionsCyclesPayRequest');
const SubscriptionsCyclesPayResponse = require('../lib/Models/SubscriptionsCyclesPayResponse');
const SubscriptionsCyclesResponse = require('../lib/Models/SubscriptionsCyclesResponse');
const SubscriptionsCyclesResponse2 = require('../lib/Models/SubscriptionsCyclesResponse2');
const SubscriptionsDiscountsRequest = require('../lib/Models/SubscriptionsDiscountsRequest');
const SubscriptionsDiscountsResponse = require('../lib/Models/SubscriptionsDiscountsResponse');
const SubscriptionsGatewayAffiliationIdRequest =
  require('../lib/Models/SubscriptionsGatewayAffiliationIdRequest');
const SubscriptionsIncrementsRequest = require('../lib/Models/SubscriptionsIncrementsRequest');
const SubscriptionsIncrementsResponse = require('../lib/Models/SubscriptionsIncrementsResponse');
const SubscriptionsItemsRequest = require('../lib/Models/SubscriptionsItemsRequest');
const SubscriptionsItemsRequest1 = require('../lib/Models/SubscriptionsItemsRequest1');
const SubscriptionsItemsResponse3 = require('../lib/Models/SubscriptionsItemsResponse3');
const SubscriptionsItemsUsagesResponse = require('../lib/Models/SubscriptionsItemsUsagesResponse');
const SubscriptionsItemsUsagesResponse1 =
  require('../lib/Models/SubscriptionsItemsUsagesResponse1');
const SubscriptionsItemsUsagesUsageIdResponse =
  require('../lib/Models/SubscriptionsItemsUsagesUsageIdResponse');
const SubscriptionsMetadataRequest = require('../lib/Models/SubscriptionsMetadataRequest');
const SubscriptionsMinimumPriceRequest = require('../lib/Models/SubscriptionsMinimumPriceRequest');
const SubscriptionsPartialInvoiceResponse =
  require('../lib/Models/SubscriptionsPartialInvoiceResponse');
const SubscriptionsPaymentMethodRequest =
  require('../lib/Models/SubscriptionsPaymentMethodRequest');
const SubscriptionsPeriodsLatestEndAtRequest =
  require('../lib/Models/SubscriptionsPeriodsLatestEndAtRequest');
const SubscriptionsRequest = require('../lib/Models/SubscriptionsRequest');
const SubscriptionsRequest1 = require('../lib/Models/SubscriptionsRequest1');
const SubscriptionsResponse3 = require('../lib/Models/SubscriptionsResponse3');
const SubscriptionsStartAtRequest = require('../lib/Models/SubscriptionsStartAtRequest');
const ThreedSecure = require('../lib/Models/ThreedSecure');
const ThreedSecure1 = require('../lib/Models/ThreedSecure1');
const Token = require('../lib/Models/Token');
const TokensRequest = require('../lib/Models/TokensRequest');
const TokensResponse = require('../lib/Models/TokensResponse');
const Usages = require('../lib/Models/Usages');
const Voucher = require('../lib/Models/Voucher');
const ErrorException = require('../lib/Exceptions/ErrorException');

const classMap = {
    ListSubscriptionsResponse,
    UpdatePriceBracketRequest,
    GetPlanResponse,
    CreatePhonesRequest,
    UpdateMetadataRequest,
    GetCheckoutPaymentSettingsResponse,
    UpdateCustomerRequest,
    CreateBoletoPaymentRequest,
    CreateDiscountRequest,
    CreateIncrementRequest,
    ListIncrementsResponse,
    GetGatewayResponseResponse,
    GetPaymentAuthenticationResponse,
    UpdateSubscriptionPaymentMethodRequest,
    GetChargeResponse,
    CreateDeviceRequest,
    GetLocationResponse,
    GetUsagesDetailsResponse,
    CreatePaymentAuthenticationRequest,
    CreateApplePayRequest,
    UpdateSubscriptionMinimumPriceRequest,
    CreateCancelChargeRequest,
    GetThreeDSecureResponse,
    GetCheckoutDebitCardPaymentResponse,
    CreateSplitOptionsRequest,
    CreateGooglePayHeaderRequest,
    GetInvoiceResponse,
    ListInvoicesResponse,
    CreatePriceBracketRequest,
    CreateCheckoutBoletoPaymentRequest,
    CreateBankAccountRequest,
    ListAnticipationResponse,
    CreateLocationRequest,
    UpdateTransferSettingsRequest,
    CreatePaymentRequest,
    GetAddressResponse,
    GetCheckoutBoletoPaymentResponse,
    UpdateSubscriptionItemRequest,
    CreateSetupRequest,
    CreatePricingSchemeRequest,
    UpdatePricingSchemeRequest,
    GetPlanItemResponse,
    GetBankTransferTransactionResponse,
    GetTransferResponse,
    CreateSubscriptionItemRequest,
    CreateSubscriptionRequest,
    CreateOrderRequest,
    CreateRecipientRequest,
    CreateDebitCardPaymentRequest,
    GetDebitCardTransactionResponse,
    CreateOrderItemRequest,
    GetTransactionReportFileResponse,
    ListUsagesResponse,
    ListCardsResponse,
    GetPriceBracketResponse,
    UpdateChargeCardRequest,
    UpdateRecipientRequest,
    GetAnticipationLimitResponse,
    CreateCancelChargeSplitRulesRequest,
    GetAnticipationResponse,
    CreateCheckoutCardInstallmentOptionRequest,
    CreateCheckoutDebitCardPaymentRequest,
    CreateAnticipationRequest,
    UpdateOrderStatusRequest,
    UpdateSubscriptionDueDaysRequest,
    ListChargeTransactionsResponse,
    ListCyclesResponse,
    CreateCardOptionsRequest,
    GetPhoneResponse,
    CreateCardTokenRequest,
    GetTokenResponse,
    GetRecipientResponse,
    GetIncrementResponse,
    GetPeriodResponse,
    UpdateChargePaymentMethodRequest,
    GetTransactionResponse,
    GetCheckoutPaymentResponse,
    CreateCardRequest,
    GetAccessTokenResponse,
    ListChargesResponse,
    GetOrderResponse,
    CreatePlanItemRequest,
    GetBillingAddressResponse,
    CreateApplePayHeaderRequest,
    CreateChargeRequest,
    CreateCustomerRequest,
    CreateCancelSubscriptionRequest,
    ListAccessTokensResponse,
    CreateTransferRequest,
    ListRecipientResponse,
    GetBalanceResponse,
    GetUsageResponse,
    CreateCreditCardPaymentRequest,
    ListDiscountsResponse,
    CreateUsageRequest,
    GetSubscriptionResponse,
    GetSubscriptionItemResponse,
    GetCardResponse,
    GetSplitResponse,
    CreateCheckoutPaymentRequest,
    CreateCheckoutBankTransferRequest,
    ListPlansResponse,
    CreateAccessTokenRequest,
    GetDiscountResponse,
    GetVoucherTransactionResponse,
    CreateTokenRequest,
    UpdateInvoiceStatusRequest,
    UpdateAddressRequest,
    GetBoletoTransactionResponse,
    GetInvoiceItemResponse,
    GetCheckoutCreditCardPaymentResponse,
    UpdateCardRequest,
    GetSetupResponse,
    CreatePlanRequest,
    CreateVoucherPaymentRequest,
    CreateBankTransferPaymentRequest,
    CreateShippingRequest,
    GetShippingResponse,
    CreateSplitRequest,
    CreateInvoiceRequest,
    UpdateSubscriptionBillingDateRequest,
    ListAddressesResponse,
    GetGatewayErrorResponse,
    CreatePeriodRequest,
    CreateCheckoutCreditCardPaymentRequest,
    CreateAntifraudRequest,
    GetAntifraudResponse,
    UpdatePlanItemRequest,
    CreateAddressRequest,
    GetAnticipationLimitsResponse,
    UpdateSubscriptionAffiliationIdRequest,
    CreateCashPaymentRequest,
    CreateConfirmPaymentRequest,
    GetCashTransactionResponse,
    UpdateCurrentCycleStatusRequest,
    GetCheckoutBankTransferPaymentResponse,
    GetCheckoutCardInstallmentOptionsResponse,
    ListSubscriptionItemsResponse,
    UpdateSubscriptionCardRequest,
    GetCustomerResponse,
    CreatePhoneRequest,
    GetPhonesResponse,
    CreateCaptureChargeRequest,
    GetSafetyPayTransactionResponse,
    ListTransferResponse,
    GetDeviceResponse,
    UpdateOrderItemRequest,
    ListUsagesDetailsResponse,
    CreateTransferSettingsRequest,
    CreateTransactionReportFileRequest,
    ListTransactionsFilesResponse,
    CreateGooglePayRequest,
    UpdateChargeDueDateRequest,
    ListCustomersResponse,
    GetPricingSchemeResponse,
    UpdateRecipientBankAccountRequest,
    CreateThreeDSecureRequest,
    GetCreditCardTransactionResponse,
    CreateCardPaymentContactlessRequest,
    GetBankAccountResponse,
    ListOrderResponse,
    ListTransactionsResponse,
    PagingResponse,
    UpdatePlanRequest,
    GetCardTokenResponse,
    GetGatewayRecipientResponse,
    UpdateSubscriptionStartAtRequest,
    UpdateCurrentCycleEndDateRequest,
    CreateClearSaleRequest,
    GetOrderItemResponse,
    CreateEmvDataDecryptRequest,
    CreateEmvDataTlvDecryptRequest,
    CreateCardPaymentContactlessPOIRequest,
    CreateEmvDataDukptDecryptRequest,
    CreateEmvDecryptRequest,
    GetUsageReportResponse,
    GetChargesSummaryResponse,
    CreateWithdrawRequest,
    GetWithdrawTargetResponse,
    GetWithdrawSourceResponse,
    GetWithdrawResponse,
    GetTransferSourceResponse,
    GetTransferTargetResponse,
    GetTransfer,
    CreateTransfer,
    ListTransfers,
    ListWithdrawals,
    CreatePrivateLabelPaymentRequest,
    GetPrivateLabelTransactionResponse,
    CreateAutomaticAnticipationSettingsRequest,
    UpdateAutomaticAnticipationSettingsRequest,
    GetAutomaticAnticipationResponse,
    GetSplitOptionsResponse,
    CreateSubMerchantRequest,
    GetPixTransactionResponse,
    PixAdditionalInformation,
    CreatePixPaymentRequest,
    GetTransferSettingsResponse,
    CreateSubscriptionSplitRequest,
    GetSubscriptionSplitResponse,
    UpdateSubscriptionSplitRequest,
    CancelSplitRequest,
    GetPixPayerResponse,
    GetPixBankAccountResponse,
    GetInterestResponse,
    GetFineResponse,
    CreateInterestRequest,
    CreateFineRequest,
    Address,
    Address1,
    ApplePay,
    Authentication,
    Authentication2,
    BankAccount,
    BankAccount1,
    BankTransfer,
    BankTransfer1,
    BankTransfer2,
    BillingAddress,
    BillingAddress1,
    Billingaddress3,
    Boleto1,
    Card,
    Card1,
    Card9,
    Card11,
    Charge,
    ChargesCaptureRequest,
    ChargesCaptureResponse,
    ChargesCardRequest,
    ChargesCardResponse,
    ChargesConfirmPaymentResponse,
    ChargesDueDateRequest,
    ChargesDueDateResponse,
    ChargesMetadataRequest,
    ChargesMetadataResponse,
    ChargesPaymentMethodRequest,
    ChargesPaymentMethodResponse,
    ChargesRequest,
    ChargesRequest1,
    ChargesResponse,
    ChargesResponse2,
    ChargesRetryResponse,
    ChargesTransactionsResponse,
    Checkout,
    Contactless,
    CreditCard1,
    CreditCard2,
    CurrentCycle,
    Customer,
    Customer8,
    CustomersAccessTokensRequest,
    CustomersAccessTokensResponse,
    CustomersAccessTokensResponse1,
    CustomersAddressesRequest,
    CustomersAddressesRequest1,
    CustomersAddressesResponse,
    CustomersAddressesResponse1,
    CustomersCardsRenewResponse,
    CustomersCardsRequest,
    CustomersCardsRequest1,
    CustomersCardsResponse,
    CustomersCardsResponse1,
    CustomersMetadataRequest,
    CustomersMetadataResponse,
    CustomersRequest,
    CustomersRequest1,
    CustomersResponse,
    CustomersResponse3,
    Cycle,
    DebitCard1,
    DebitCard2,
    DefaultBankAccount,
    DefaultBankAccount1,
    Device,
    Device1,
    Fine,
    GatewayResponse,
    GooglePay,
    Header,
    Header1,
    Interest,
    Invoice,
    InvoicesMetadataRequest,
    InvoicesMetadataResponse,
    InvoicesResponse,
    InvoicesResponse2,
    InvoicesStatusResponse,
    Location,
    Max,
    Min,
    Options1,
    Options2,
    Order,
    OrdersClosedResponse,
    OrdersItemsRequest,
    OrdersItemsRequest1,
    OrdersItemsResponse,
    OrdersItemsResponse1,
    OrdersMetadataRequest,
    OrdersMetadataResponse,
    OrdersRequest,
    OrdersResponse,
    OrdersResponse1,
    Paging,
    Payment,
    Period,
    Pix,
    Plan,
    PlansItemsRequest,
    PlansItemsRequest1,
    PlansItemsResponse,
    PlansMetadataRequest,
    PlansMetadataResponse,
    PlansRequest,
    PlansRequest1,
    PlansResponse,
    PlansResponse1,
    PriceBracket,
    PricingScheme,
    PricingScheme3,
    PricingScheme4,
    PrivateLabel,
    Recipient,
    RecipientsAnticipationLimitsResponse,
    RecipientsAnticipationsRequest,
    RecipientsAnticipationsResponse,
    RecipientsAnticipationsResponse1,
    RecipientsAutomaticAnticipationSettingsResponse,
    RecipientsBalanceResponse,
    RecipientsCodeResponse,
    RecipientsDefaultBankAccountRequest,
    RecipientsDefaultBankAccountResponse,
    RecipientsMetadataRequest,
    RecipientsMetadataResponse,
    RecipientsRequest,
    RecipientsRequest1,
    RecipientsResponse,
    RecipientsResponse1,
    RecipientsTransferSettingsResponse,
    RecipientsTransfersRequest,
    RecipientsTransfersResponse,
    RecipientsTransfersResponse1,
    Setup,
    Setup1,
    Shipping,
    Shipping3,
    Split,
    Submerchant,
    SubscriptionsBillingDateRequest,
    SubscriptionsCardRequest,
    SubscriptionsCyclesPayRequest,
    SubscriptionsCyclesPayResponse,
    SubscriptionsCyclesResponse,
    SubscriptionsCyclesResponse2,
    SubscriptionsDiscountsRequest,
    SubscriptionsDiscountsResponse,
    SubscriptionsGatewayAffiliationIdRequest,
    SubscriptionsIncrementsRequest,
    SubscriptionsIncrementsResponse,
    SubscriptionsItemsRequest,
    SubscriptionsItemsRequest1,
    SubscriptionsItemsResponse3,
    SubscriptionsItemsUsagesResponse,
    SubscriptionsItemsUsagesResponse1,
    SubscriptionsItemsUsagesUsageIdResponse,
    SubscriptionsMetadataRequest,
    SubscriptionsMinimumPriceRequest,
    SubscriptionsPartialInvoiceResponse,
    SubscriptionsPaymentMethodRequest,
    SubscriptionsPeriodsLatestEndAtRequest,
    SubscriptionsRequest,
    SubscriptionsRequest1,
    SubscriptionsResponse3,
    SubscriptionsStartAtRequest,
    ThreedSecure,
    ThreedSecure1,
    Token,
    TokensRequest,
    TokensResponse,
    Usages,
    Voucher,
    ErrorException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
