/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GetAntifraudResponse {
  status: string;
  returnCode: string;
  returnMessage: string;
  providerName: string;
  score: string;
}

export const getAntifraudResponseSchema: Schema<GetAntifraudResponse> = object({
  status: ['status', string()],
  returnCode: ['return_code', string()],
  returnMessage: ['return_message', string()],
  providerName: ['provider_name', string()],
  score: ['score', string()],
});
