/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** Bank transfer checkout response */
export interface GetCheckoutBankTransferPaymentResponse {
  /** bank list response */
  bank: string[];
}

export const getCheckoutBankTransferPaymentResponseSchema: Schema<GetCheckoutBankTransferPaymentResponse> = object(
  { bank: ['bank', array(string())] }
);
