/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface GetCheckoutCardInstallmentOptionsResponse {
  /** Número de parcelas */
  number: string;
  /** Valor total da compra */
  total: number;
}

export const getCheckoutCardInstallmentOptionsResponseSchema: Schema<GetCheckoutCardInstallmentOptionsResponse> = object(
  { number: ['number', string()], total: ['total', number()] }
);
