/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface GetPhoneResponse {
  countryCode?: string;
  number?: string;
  areaCode?: string;
}

export const getPhoneResponseSchema: Schema<GetPhoneResponse> = object({
  countryCode: ['country_code', optional(string())],
  number: ['number', optional(string())],
  areaCode: ['area_code', optional(string())],
});
