/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface GetTransferSettingsResponse {
  transferEnabled: boolean;
  transferInterval: string;
  transferDay: number;
}

export const getTransferSettingsResponseSchema: Schema<GetTransferSettingsResponse> = object(
  {
    transferEnabled: ['transfer_enabled', boolean()],
    transferInterval: ['transfer_interval', string()],
    transferDay: ['transfer_day', number()],
  }
);
