/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, lazy, number, object, Schema, string } from '../schema';
import {
  GetBankAccountResponse,
  getBankAccountResponseSchema,
} from './getBankAccountResponse';

/** Transfer response */
export interface GetTransferResponse {
  /** Id */
  id: string;
  /** Transfer amount */
  amount: number;
  /** Transfer status */
  status: string;
  /** Transfer creation date */
  createdAt: string;
  /** Transfer last update date */
  updatedAt: string;
  /** Bank account */
  bankAccount: GetBankAccountResponse;
  /** Metadata */
  metadata: Record<string, string>;
}

export const getTransferResponseSchema: Schema<GetTransferResponse> = object({
  id: ['id', string()],
  amount: ['amount', number()],
  status: ['status', string()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
  bankAccount: ['bank_account', lazy(() => getBankAccountResponseSchema)],
  metadata: ['metadata', dict(string())],
});
