/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  discriminatedGetTransactionResponseSchema,
} from '../models/discriminatedSchemas';
import { array, lazy, object, Schema } from '../schema';
import { GetTransactionResponse } from './getTransactionResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing transactions */
export interface ListTransactionsResponse {
  /** The transaction objects */
  data: GetTransactionResponse[];
  /** Paging object */
  paging: PagingResponse;
}

export const listTransactionsResponseSchema: Schema<any> = object({
  data: ['data', array(lazy(() => discriminatedGetTransactionResponseSchema))],
  paging: ['paging', lazy(() => pagingResponseSchema)],
});
