/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { GetPlanResponse, getPlanResponseSchema } from './getPlanResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing plans */
export interface ListPlansResponse {
  /** The plan objects */
  data: GetPlanResponse[];
  /** Paging object */
  paging: PagingResponse;
}

export const listPlansResponseSchema: Schema<ListPlansResponse> = object({
  data: ['data', array(lazy(() => getPlanResponseSchema))],
  paging: ['paging', lazy(() => pagingResponseSchema)],
});
