/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import {
  GetTransactionReportFileResponse,
  getTransactionReportFileResponseSchema,
} from './getTransactionReportFileResponse';
import { PagingResponse, pagingResponseSchema } from './pagingResponse';

/** Response object for listing of transactions files */
export interface ListTransactionsFilesResponse {
  data: GetTransactionReportFileResponse[];
  /** Paging object */
  paging: PagingResponse;
}

export const listTransactionsFilesResponseSchema: Schema<ListTransactionsFilesResponse> = object(
  {
    data: ['data', array(lazy(() => getTransactionReportFileResponseSchema))],
    paging: ['paging', lazy(() => pagingResponseSchema)],
  }
);
