/**
 * MundiAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

/** Object used for returning lists of objects with pagination */
export interface PagingResponse {
  /** Total number of pages */
  total: number;
  /** Previous page */
  previous: string;
  /** Next page */
  next: string;
}

export const pagingResponseSchema: Schema<PagingResponse> = object({
  total: ['total', number()],
  previous: ['previous', string()],
  next: ['next', string()],
});
